#DB Configuration
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/microservice 
    username: root 
    password: root
  redis:
    host: 192.168.2.100
    port: 6379
  activemq:
    broker-url: tcp://192.168.2.100:61616
#logging
logging:
  level: 
    com.itheima.springboot: debug